spring:
  application:
    name: orders-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xcplus_orders?serverTimezone=UTC&userUnicode=true&useSSL=false&
    username: root
    password: 19911120Aa,
# 日志文件配置路径
logging:
  config: classpath:log4j2-dev.xml

#xxl:
#  job:
#    admin:
#      addresses: http://127.0.0.1:8088/xxl-job-admin
#    executor:
#      appname: coursepublish-job
#      address:
#      ip:
#      port: 8999
#      logpath: /data/applogs/xxl-job/jobhandler
#      logretentiondays: 30
#    accessToken: default_token
test_config:
  a: 2a
  b: 2b
  c: 2c

#feign:
#  client:
#    config:
#      default: # default全局的配置
#        loggerLevel: BASIC # 日志级别，BASIC就是基本的请求和响应信息
#  hystrix:
#    enabled: true
#  circuitbreaker:
#    enabled: true
#  httpclient:
#    enabled: true # 开启feign对HttpClient的支持
#    max-connections: 200 # 最大的连接数
#    max-connections-per-route: 50 # 每个路径的最大连接数